import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head } from '@inertiajs/react';
import { BarChart3, TrendingUp, Clock, Award } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
const breadcrumbs = [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Productivity', href: '/productivity' }];
export default function Productivity() {
    return (<AppLayout breadcrumbs={breadcrumbs}><Head title="Productivity" /><div className="flex flex-1 flex-col gap-4 p-4"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Productivity Tracker</h1><p className="text-muted-foreground">Monitor your scholarly activity and progress</p></div></div><div className="grid gap-4 md:grid-cols-4"><Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Productivity Score</CardTitle><Award className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">0</div><p className="text-xs text-muted-foreground">This week</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Study Time</CardTitle><Clock className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">0h</div><p className="text-xs text-muted-foreground">This week</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Tasks Completed</CardTitle><TrendingUp className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">0</div><p className="text-xs text-muted-foreground">This week</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Current Streak</CardTitle><BarChart3 className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">0 days</div><p className="text-xs text-muted-foreground">Keep it up!</p></CardContent></Card></div><Card><CardHeader><CardTitle>Activity Level</CardTitle><CardDescription>Your productivity status</CardDescription></CardHeader><CardContent><div className="flex items-center justify-center py-8"><Badge variant="outline" className="text-lg px-6 py-2">No activity yet - Start tracking your work!</Badge></div></CardContent></Card></div></AppLayout>);
}
